services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    shm_size: '1gb'      # <-- add this
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - whatsapp_auth:/app/.wwebjs_auth
      - whatsapp_cache:/app/.wwebjs_cache
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/server.js"]

  db:
    image: postgres:15
    container_name: phoneo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: phoneo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d phoneo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  whatsapp_auth:
  whatsapp_cache: